"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _admin_content from './admin-content.bones.json'
import _company_content from './company-content.bones.json'
import _admin_portal from './admin-portal.bones.json'
import _company_portal from './company-portal.bones.json'
import _workspace_hub from './workspace-hub.bones.json'
import _chat_portal from './chat-portal.bones.json'
import _module_portal from './module-portal.bones.json'
import _company_team_table from './company-team-table.bones.json'

configureBoneyard({"color":"rgba(0,0,0,0.08)","darkColor":"rgba(255,255,255,0.06)","animate":"shimmer","shimmerColor":"rgba(0,0,0,0.04)","darkShimmerColor":"rgba(255,255,255,0.1)","speed":"2s","shimmerAngle":110,"transition":true})

registerBones({
  "admin-content": _admin_content,
  "company-content": _company_content,
  "admin-portal": _admin_portal,
  "company-portal": _company_portal,
  "workspace-hub": _workspace_hub,
  "chat-portal": _chat_portal,
  "module-portal": _module_portal,
  "company-team-table": _company_team_table,
})
