import type { AuditEntry } from "./types";

export const SEED_AUDIT: AuditEntry[] = [
    {
        id: "aud-001",
        at: "2026-08-14T08:12:00.000Z",
        actor: "super-admin",
        action: "company.access_approve",
        targetType: "company",
        targetId: "co-008",
        targetLabel: "Northspan Works",
        detail: "Approved Maya Chen — owner can choose a package",
    },
    {
        id: "aud-002",
        at: "2026-08-13T16:40:00.000Z",
        actor: "super-admin",
        action: "tokens.topup_approve",
        targetType: "company",
        targetId: "co-001",
        targetLabel: "Acme Builders",
        detail: "Approved 10,000 extra tokens",
    },
    {
        id: "aud-003",
        at: "2026-08-13T11:05:00.000Z",
        actor: "ops",
        action: "ticket.assign",
        targetType: "ticket",
        targetId: "tkt-001",
        targetLabel: "Token usage spike",
        detail: "Assigned to Aisha Khan",
    },
    {
        id: "aud-004",
        at: "2026-08-12T09:18:00.000Z",
        actor: "super-admin",
        action: "billing.retry_invoice",
        targetType: "invoice",
        targetId: "inv-003",
        targetLabel: "Cedar Construction",
        detail: "Retried past-due invoice inv-003",
    },
    {
        id: "aud-005",
        at: "2026-08-11T14:22:00.000Z",
        actor: "acme-admin",
        action: "user.invite",
        targetType: "user",
        targetId: "u-004",
        targetLabel: "David Kim",
        detail: "Invited david.kim@acmebuilders.com as viewer",
    },
    {
        id: "aud-006",
        at: "2026-08-10T10:00:00.000Z",
        actor: "super-admin",
        action: "company.plan_change",
        targetType: "company",
        targetId: "co-004",
        targetLabel: "Delta Engineering",
        detail: "Moved from Pro to Enterprise",
    },
    {
        id: "aud-007",
        at: "2026-08-08T17:31:00.000Z",
        actor: "super-admin",
        action: "company.suspend",
        targetType: "company",
        targetId: "co-007",
        targetLabel: "Harbor Civils",
        detail: "Suspended after dunning exhausted",
    },
    {
        id: "aud-008",
        at: "2026-08-07T08:44:00.000Z",
        actor: "super-admin",
        action: "tokens.rates_update",
        targetType: "company",
        targetId: "platform",
        targetLabel: "Platform sell rate",
        detail: "Sell rate set to 80 tokens / $1",
    },
];
