import type { ActivityItem, Company, User } from "./types";

export const COMPANIES: Company[] = [
  {
    id: "co-001",
    name: "Acme Builders",
    industry: "Construction",
    planId: "pro",
    status: "active",
    usersCount: 4,
    storageLimitGb: 80,
    storageUsedGb: 50,
    tokenLimit: 1878,
    tokensUsed: 1280,
    createdAt: "2025-06-12",
    addOns: ["chronology", "forensic"],
    trialUsage: {},
  },
  {
    id: "co-002",
    name: "Beta Labs",
    industry: "Research",
    planId: "demo",
    status: "trial",
    usersCount: 2,
    storageLimitGb: 20,
    storageUsedGb: 1,
    tokenLimit: 376,
    tokensUsed: 42,
    createdAt: "2026-07-01",
    addOns: [],
    trialUsage: {},
  },
  {
    id: "co-003",
    name: "Cedar Construction",
    industry: "Construction",
    planId: "foundation",
    status: "active",
    usersCount: 3,
    storageLimitGb: 20,
    storageUsedGb: 16,
    tokenLimit: 939,
    tokensUsed: 900,
    createdAt: "2025-11-03",
    addOns: [],
    trialUsage: {},
  },
  {
    id: "co-004",
    name: "Delta Engineering",
    industry: "Engineering",
    planId: "enterprise",
    status: "active",
    usersCount: 5,
    storageLimitGb: 150,
    storageUsedGb: 90,
    tokenLimit: 3756,
    tokensUsed: 2000,
    createdAt: "2024-09-18",
    addOns: ["chronology"],
    trialUsage: {},
  },
  {
    id: "co-005",
    name: "Echo Materials",
    industry: "Manufacturing",
    planId: "foundation",
    status: "suspended",
    usersCount: 2,
    storageLimitGb: 20,
    storageUsedGb: 18,
    tokenLimit: 939,
    tokensUsed: 700,
    createdAt: "2026-02-14",
    addOns: [],
    trialUsage: {},
  },
  {
    id: "co-006",
    name: "Foxtrot Demolition",
    industry: "Demolition",
    planId: "pro",
    status: "trial",
    usersCount: 2,
    storageLimitGb: 80,
    storageUsedGb: 20,
    tokenLimit: 1878,
    tokensUsed: 200,
    createdAt: "2026-06-20",
    addOns: [],
    trialUsage: {},
  },
  {
    id: "co-007",
    name: "Gulf Coast Site Prep",
    industry: "Land Development",
    planId: "demo",
    status: "suspended",
    usersCount: 1,
    storageLimitGb: 20,
    storageUsedGb: 2,
    tokenLimit: 376,
    tokensUsed: 100,
    createdAt: "2025-03-08",
    addOns: [],
    trialUsage: {},
  },
];

export const USERS: User[] = [
  {
    id: "u-001",
    name: "Ada Lovelace",
    email: "ada@acmebuilders.com",
    companyId: "co-001",
    role: "admin",
    status: "active",
    lastLoginAt: "2026-08-03",
    createdAt: "2025-06-15",
  },
  {
    id: "u-002",
    name: "Ben Carter",
    email: "ben.carter@acmebuilders.com",
    companyId: "co-001",
    role: "member",
    status: "active",
    lastLoginAt: "2026-08-02",
    createdAt: "2025-08-01",
  },
  {
    id: "u-003",
    name: "Clara Nguyen",
    email: "clara@acmebuilders.com",
    companyId: "co-001",
    role: "member",
    status: "active",
    lastLoginAt: "2026-07-28",
    createdAt: "2025-10-12",
  },
  {
    id: "u-004",
    name: "David Kim",
    email: "david.kim@acmebuilders.com",
    companyId: "co-001",
    role: "viewer",
    status: "pending",
    lastLoginAt: null,
    createdAt: "2026-07-20",
  },
  {
    id: "u-005",
    name: "Elena Rossi",
    email: "elena@betalabs.io",
    companyId: "co-002",
    role: "admin",
    status: "active",
    lastLoginAt: "2026-08-01",
    createdAt: "2026-07-01",
  },
  {
    id: "u-006",
    name: "Frank Miller",
    email: "frank@betalabs.io",
    companyId: "co-002",
    role: "member",
    status: "pending",
    lastLoginAt: null,
    createdAt: "2026-07-15",
  },
  {
    id: "u-007",
    name: "Grace Patel",
    email: "grace@cedarconstruction.com",
    companyId: "co-003",
    role: "admin",
    status: "active",
    lastLoginAt: "2026-08-04",
    createdAt: "2025-11-05",
  },
  {
    id: "u-008",
    name: "Henry Walsh",
    email: "henry@cedarconstruction.com",
    companyId: "co-003",
    role: "member",
    status: "active",
    lastLoginAt: "2026-08-03",
    createdAt: "2026-01-20",
  },
  {
    id: "u-009",
    name: "Iris Chen",
    email: "iris@cedarconstruction.com",
    companyId: "co-003",
    role: "viewer",
    status: "active",
    lastLoginAt: "2026-07-30",
    createdAt: "2026-03-10",
  },
  {
    id: "u-010",
    name: "James Okonkwo",
    email: "james@deltaeng.com",
    companyId: "co-004",
    role: "admin",
    status: "active",
    lastLoginAt: "2026-08-04",
    createdAt: "2024-09-20",
  },
  {
    id: "u-011",
    name: "Karen Liu",
    email: "karen@deltaeng.com",
    companyId: "co-004",
    role: "member",
    status: "active",
    lastLoginAt: "2026-08-02",
    createdAt: "2025-01-08",
  },
  {
    id: "u-012",
    name: "Leo Martinez",
    email: "leo@deltaeng.com",
    companyId: "co-004",
    role: "member",
    status: "active",
    lastLoginAt: "2026-07-29",
    createdAt: "2025-04-22",
  },
  {
    id: "u-013",
    name: "Maya Singh",
    email: "maya@deltaeng.com",
    companyId: "co-004",
    role: "member",
    status: "suspended",
    lastLoginAt: "2026-06-10",
    createdAt: "2025-06-01",
  },
  {
    id: "u-014",
    name: "Noah Brooks",
    email: "noah@deltaeng.com",
    companyId: "co-004",
    role: "viewer",
    status: "active",
    lastLoginAt: "2026-07-25",
    createdAt: "2026-02-03",
  },
  {
    id: "u-015",
    name: "Olivia Tate",
    email: "olivia@echo-materials.com",
    companyId: "co-005",
    role: "admin",
    status: "suspended",
    lastLoginAt: "2026-05-18",
    createdAt: "2026-02-14",
  },
  {
    id: "u-016",
    name: "Paul Jensen",
    email: "paul@echo-materials.com",
    companyId: "co-005",
    role: "member",
    status: "suspended",
    lastLoginAt: "2026-05-15",
    createdAt: "2026-03-01",
  },
  {
    id: "u-017",
    name: "Quinn Harper",
    email: "quinn@foxtrotdemo.com",
    companyId: "co-006",
    role: "admin",
    status: "active",
    lastLoginAt: "2026-08-01",
    createdAt: "2026-06-20",
  },
  {
    id: "u-018",
    name: "Rita Alvarez",
    email: "rita@foxtrotdemo.com",
    companyId: "co-006",
    role: "member",
    status: "pending",
    lastLoginAt: null,
    createdAt: "2026-07-01",
  },
  {
    id: "u-019",
    name: "Sam Ortiz",
    email: "sam@gulfcoastprep.com",
    companyId: "co-007",
    role: "admin",
    status: "suspended",
    lastLoginAt: "2025-12-01",
    createdAt: "2025-03-08",
  },
];

export const ACTIVITIES: ActivityItem[] = [
  {
    id: "act-001",
    text: "Acme Builders upgraded to Business plan",
    at: "2026-07-10T14:22:00.000Z",
  },
  {
    id: "act-002",
    text: "Beta Labs started a 14-day trial on Free plan",
    at: "2026-07-01T09:00:00.000Z",
  },
  {
    id: "act-003",
    text: "Cedar Construction reached 96% token usage",
    at: "2026-08-03T16:45:00.000Z",
  },
  {
    id: "act-004",
    text: "Echo Materials account suspended for billing",
    at: "2026-05-20T11:30:00.000Z",
  },
  {
    id: "act-005",
    text: "Delta Engineering added 2 new users",
    at: "2026-02-03T08:15:00.000Z",
  },
  {
    id: "act-006",
    text: "Foxtrot Demolition started Business trial",
    at: "2026-06-20T10:00:00.000Z",
  },
];
