-- COAir core relational schema for Supabase / PostgreSQL.
-- Idempotent: safe to run on every startup.

-- ── Users & usage ───────────────────────────────────────────
CREATE TABLE IF NOT EXISTS users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        TEXT UNIQUE NOT NULL,
    display_name    TEXT,
    password_hash   TEXT NOT NULL,
    role            TEXT NOT NULL DEFAULT 'user',
    token_limit     BIGINT NOT NULL DEFAULT 1000000,
    features_json   TEXT NOT NULL DEFAULT '{}',
    is_active       INTEGER NOT NULL DEFAULT 1,
    token_epoch     INTEGER NOT NULL DEFAULT 0,
    supabase_user_id TEXT,
    created_at      TEXT NOT NULL,
    updated_at      TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS user_usage (
    username          TEXT PRIMARY KEY REFERENCES users(username) ON DELETE CASCADE,
    prompt_tokens     BIGINT NOT NULL DEFAULT 0,
    completion_tokens BIGINT NOT NULL DEFAULT 0,
    total_calls       BIGINT NOT NULL DEFAULT 0,
    updated_at        TEXT NOT NULL
);

-- ── Billing ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS billing_accounts (
    username                 TEXT PRIMARY KEY REFERENCES users(username) ON DELETE CASCADE,
    plan_type                TEXT NOT NULL DEFAULT 'legacy',
    credits_granted_micro    BIGINT NOT NULL DEFAULT 0,
    credits_balance_micro    BIGINT NOT NULL DEFAULT 0,
    markup_bps               INTEGER NOT NULL DEFAULT 3000,
    storage_limit_bytes      BIGINT NOT NULL DEFAULT 0,
    storage_used_bytes       BIGINT NOT NULL DEFAULT 0,
    model_policy             TEXT NOT NULL DEFAULT '',
    provider_key_ref         TEXT NOT NULL DEFAULT '',
    created_at               TEXT NOT NULL,
    updated_at               TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS billing_ledger (
    event_id                 TEXT PRIMARY KEY,
    idempotency_key          TEXT UNIQUE,
    username                 TEXT NOT NULL REFERENCES users(username) ON DELETE CASCADE,
    project_id               TEXT,
    run_id                   TEXT,
    job_id                   TEXT,
    event_type               TEXT NOT NULL,
    task_type                TEXT,
    provider                 TEXT,
    model                    TEXT,
    prompt_tokens            BIGINT NOT NULL DEFAULT 0,
    completion_tokens        BIGINT NOT NULL DEFAULT 0,
    reasoning_tokens         BIGINT NOT NULL DEFAULT 0,
    cached_tokens            BIGINT NOT NULL DEFAULT 0,
    pricing_version          TEXT,
    provider_cost_nanos      BIGINT NOT NULL DEFAULT 0,
    retail_credit_micros     BIGINT NOT NULL DEFAULT 0,
    debited_credit_micros    BIGINT NOT NULL DEFAULT 0,
    uncovered_credit_micros  BIGINT NOT NULL DEFAULT 0,
    markup_bps               INTEGER NOT NULL DEFAULT 0,
    usage_source             TEXT NOT NULL DEFAULT 'provider',
    note                     TEXT,
    created_at               TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_billing_ledger_user_time
    ON billing_ledger(username, created_at);
CREATE INDEX IF NOT EXISTS idx_billing_ledger_project_time
    ON billing_ledger(project_id, created_at);

CREATE OR REPLACE FUNCTION billing_ledger_block_mutations()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'billing ledger is append-only';
END;
$$;

DROP TRIGGER IF EXISTS billing_ledger_no_update ON billing_ledger;
CREATE TRIGGER billing_ledger_no_update
    BEFORE UPDATE ON billing_ledger
    FOR EACH ROW EXECUTE FUNCTION billing_ledger_block_mutations();

DROP TRIGGER IF EXISTS billing_ledger_no_delete ON billing_ledger;
CREATE TRIGGER billing_ledger_no_delete
    BEFORE DELETE ON billing_ledger
    FOR EACH ROW EXECUTE FUNCTION billing_ledger_block_mutations();

CREATE TABLE IF NOT EXISTS storage_objects (
    object_id       TEXT PRIMARY KEY,
    username        TEXT NOT NULL REFERENCES users(username) ON DELETE CASCADE,
    project_id      TEXT NOT NULL,
    file_id         TEXT NOT NULL,
    file_path       TEXT NOT NULL,
    size_bytes      BIGINT NOT NULL,
    created_at      TEXT NOT NULL,
    deleted_at      TEXT,
    UNIQUE(project_id, file_id)
);

CREATE INDEX IF NOT EXISTS idx_storage_objects_user
    ON storage_objects(username, deleted_at);

-- ── Organizations & projects ────────────────────────────────
CREATE TABLE IF NOT EXISTS organizations (
    org_id                  TEXT PRIMARY KEY,
    name                    TEXT NOT NULL,
    slug                    TEXT NOT NULL UNIQUE,
    default_plan_type       TEXT NOT NULL DEFAULT 'demo'
                            CHECK(default_plan_type IN ('demo','legacy')),
    default_credits         DOUBLE PRECISION NOT NULL DEFAULT 0,
    default_token_limit     BIGINT NOT NULL DEFAULT 1000000,
    default_storage_bytes   BIGINT NOT NULL DEFAULT 30000000000,
    project_limit           INTEGER NOT NULL DEFAULT 0,
    allow_member_projects   INTEGER NOT NULL DEFAULT 0,
    created_by              TEXT NOT NULL,
    created_at              TEXT NOT NULL,
    updated_at              TEXT NOT NULL,
    archived_at             TEXT
);

CREATE TABLE IF NOT EXISTS org_members (
    org_id      TEXT NOT NULL REFERENCES organizations(org_id) ON DELETE CASCADE,
    username    TEXT NOT NULL,
    role        TEXT NOT NULL CHECK(role IN ('owner','member')),
    created_at  TEXT NOT NULL,
    PRIMARY KEY(org_id, username)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_org_members_username ON org_members(username);

CREATE TABLE IF NOT EXISTS projects (
    project_id          TEXT PRIMARY KEY,
    name                TEXT NOT NULL,
    slug                TEXT NOT NULL,
    embedding_profile   TEXT NOT NULL DEFAULT 'local-bge-v1',
    created_by          TEXT NOT NULL,
    created_at          TEXT NOT NULL,
    updated_at          TEXT NOT NULL,
    archived_at         TEXT,
    org_id              TEXT
);

CREATE INDEX IF NOT EXISTS idx_projects_org ON projects(org_id, archived_at);

CREATE TABLE IF NOT EXISTS project_members (
    project_id  TEXT NOT NULL REFERENCES projects(project_id) ON DELETE CASCADE,
    username    TEXT NOT NULL,
    role        TEXT NOT NULL CHECK(role IN ('owner','editor','viewer')),
    created_at  TEXT NOT NULL,
    PRIMARY KEY(project_id, username)
);

CREATE INDEX IF NOT EXISTS idx_project_members_user
    ON project_members(username, project_id);

CREATE TABLE IF NOT EXISTS project_vector_state (
    project_id          TEXT PRIMARY KEY REFERENCES projects(project_id) ON DELETE CASCADE,
    embedding_profile   TEXT NOT NULL,
    collection_name     TEXT NOT NULL,
    status              TEXT NOT NULL DEFAULT 'empty',
    point_count         BIGINT NOT NULL DEFAULT 0,
    last_error          TEXT,
    provisioned_at      TEXT,
    updated_at          TEXT NOT NULL
);

-- ── Platform ops ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS audit_events (
    event_id TEXT PRIMARY KEY,
    at TEXT NOT NULL,
    actor TEXT NOT NULL,
    action TEXT NOT NULL,
    target_type TEXT NOT NULL,
    target_id TEXT NOT NULL,
    target_label TEXT NOT NULL,
    detail TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_audit_at ON audit_events(at DESC);

CREATE TABLE IF NOT EXISTS invoices (
    invoice_id TEXT PRIMARY KEY,
    org_id TEXT NOT NULL,
    amount_usd DOUBLE PRECISION NOT NULL,
    status TEXT NOT NULL,
    issued_at TEXT NOT NULL,
    due_at TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_invoices_org ON invoices(org_id, issued_at);

CREATE TABLE IF NOT EXISTS coupons (
    coupon_id TEXT PRIMARY KEY,
    code TEXT UNIQUE NOT NULL,
    discount_type TEXT NOT NULL,
    discount_value DOUBLE PRECISION NOT NULL,
    active INTEGER NOT NULL,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS tax_settings (
    id INTEGER PRIMARY KEY CHECK (id = 1),
    percent DOUBLE PRECISION NOT NULL,
    region_label TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS overage_policy (
    id INTEGER PRIMARY KEY CHECK (id = 1),
    mode TEXT NOT NULL,
    trigger_pct DOUBLE PRECISION NOT NULL,
    notes TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS dunning_cases (
    case_id TEXT PRIMARY KEY,
    org_id TEXT NOT NULL,
    status TEXT NOT NULL,
    failed_at TEXT NOT NULL,
    grace_ends_at TEXT NOT NULL,
    attempt_count INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS security_settings (
    id INTEGER PRIMARY KEY CHECK (id = 1),
    mfa_required INTEGER NOT NULL,
    session_timeout_minutes INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS ip_allowlist (
    entry TEXT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS api_keys (
    key_id TEXT PRIMARY KEY,
    label TEXT NOT NULL,
    prefix TEXT NOT NULL,
    last_four TEXT NOT NULL,
    key_hash TEXT NOT NULL,
    created_at TEXT NOT NULL,
    revoked_at TEXT
);

CREATE TABLE IF NOT EXISTS password_resets (
    token_hash TEXT PRIMARY KEY,
    username TEXT NOT NULL,
    expires_at TEXT NOT NULL,
    used_at TEXT
);

CREATE TABLE IF NOT EXISTS mfa_challenges (
    challenge_id TEXT PRIMARY KEY,
    username TEXT NOT NULL,
    code_hash TEXT NOT NULL,
    expires_at TEXT NOT NULL,
    used_at TEXT
);

CREATE TABLE IF NOT EXISTS email_outbox (
    outbox_id TEXT PRIMARY KEY,
    kind TEXT NOT NULL,
    recipient TEXT NOT NULL,
    subject TEXT NOT NULL,
    body TEXT NOT NULL,
    secret TEXT,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS feature_flags (
    flag_id TEXT PRIMARY KEY,
    key TEXT UNIQUE NOT NULL,
    label TEXT NOT NULL,
    enabled INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS platform_settings (
    id INTEGER PRIMARY KEY CHECK (id = 1),
    maintenance_mode INTEGER NOT NULL,
    maintenance_message TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS announcements (
    announcement_id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    body TEXT NOT NULL,
    status TEXT NOT NULL,
    created_at TEXT NOT NULL,
    published_at TEXT
);

CREATE TABLE IF NOT EXISTS topup_requests (
    request_id TEXT PRIMARY KEY,
    org_id TEXT NOT NULL,
    username TEXT NOT NULL,
    tokens INTEGER NOT NULL,
    amount_usd DOUBLE PRECISION NOT NULL,
    reason TEXT NOT NULL,
    status TEXT NOT NULL,
    created_at TEXT NOT NULL,
    resolved_at TEXT,
    resolved_by TEXT
);

CREATE INDEX IF NOT EXISTS idx_topups_status ON topup_requests(status, created_at);

CREATE TABLE IF NOT EXISTS member_token_requests (
    request_id TEXT PRIMARY KEY,
    org_id TEXT NOT NULL,
    username TEXT NOT NULL,
    tokens INTEGER NOT NULL,
    reason TEXT NOT NULL,
    status TEXT NOT NULL,
    created_at TEXT NOT NULL,
    resolved_at TEXT,
    resolved_by TEXT,
    fulfill_mode TEXT,
    donor_username TEXT,
    purchase_session_id TEXT
);

CREATE INDEX IF NOT EXISTS idx_member_token_requests_org
    ON member_token_requests(org_id, status, created_at);

-- ── Commerce ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS tickets (
    ticket_id TEXT PRIMARY KEY,
    org_id TEXT NOT NULL,
    subject TEXT NOT NULL,
    message TEXT NOT NULL,
    priority TEXT NOT NULL,
    status TEXT NOT NULL,
    assignee_id TEXT,
    created_by TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_tickets_org ON tickets(org_id, created_at);

CREATE TABLE IF NOT EXISTS packages (
    plan_id TEXT PRIMARY KEY,
    payload_json TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS token_economics (
    id INTEGER PRIMARY KEY CHECK (id = 1),
    provider_tokens_per_usd DOUBLE PRECISION NOT NULL,
    sell_tokens_per_usd DOUBLE PRECISION NOT NULL,
    updated_at TEXT NOT NULL,
    updated_by TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS access_requests (
    request_id TEXT PRIMARY KEY,
    full_name TEXT NOT NULL,
    email TEXT NOT NULL,
    company_name TEXT NOT NULL,
    status TEXT NOT NULL,
    created_at TEXT NOT NULL,
    resolved_at TEXT,
    resolved_plan_id TEXT
);

CREATE INDEX IF NOT EXISTS idx_access_requests_email ON access_requests(email, status);

CREATE TABLE IF NOT EXISTS org_subscriptions (
    org_id TEXT PRIMARY KEY,
    plan_id TEXT NOT NULL,
    needs_checkout INTEGER NOT NULL,
    sell_tokens_per_usd_override DOUBLE PRECISION,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS stripe_fulfillments (
    session_id TEXT PRIMARY KEY,
    org_id TEXT NOT NULL,
    kind TEXT NOT NULL,
    payload_json TEXT NOT NULL,
    created_at TEXT NOT NULL
);
